export default [
    "No, really we *still* don't have VBucks",
    "Error 418: I'm a teapot",
    "7777777777777",
    "[TypeError] humour not found (420:69)",
    "SHU UHSU HSUFHDpebnfgwpeew",
    "Fluting since 2020",
    "nom",
    "uwu",
    "owowowowowowowo",
    "who the fuck made this thing",
    "Cheer1 Cheer1 Cheer1 Cheer1 Cheer1 Cheer1",
    "nice logo",
    "elseif elseif elseif elseif elseif elseif",
    "I, EvaX, humbly submit a toas-",
    "one Yamm_",
    "Compiler error at Line 52",
    "bodge",
    "delete this",
    "get in the jar",
    "EvaX was here",
    "600 When 600 When 600 When 600 When",
    "Cannot BRUH /",
    "Don't let the Dalux bite.",
    "bodge was here - meep",
    "where are the bobux"
]
