import { Inter, JetBrains_Mono } from 'next/font/google';
import 'react-tooltip/dist/react-tooltip.css';
import '../css/globals.css';
import Navbar from '@mae/components/layout/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ preload: true, weight: ['300', '400', '500', '600', '700', '900'], subsets: ['latin']})
// const jbm = JetBrains_Mono({ preload: true, weight: ['300', '500'], subsets: ['latin']})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"/>
      </head>
      <body className={inter.className + " " + "bg-[#0c0c0c] text-gray-200"}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
